default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: sms_development
  pool: 5
  username: dhruvildave
  password: 12345
test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: sms_test
  pool: 5
  username: dhruvildave
  password: 12345
production:
  <<: *default
  database: sms_production
  username: sms
  password: <%= ENV['SMS_DATABASE_PASSWORD'] %>
